services:

  backend:
    image: skstechops/project-backend:1.0
    container_name: project-backend
    ports:
      - "8000:8000"

  frontend:
    image: skstechops/project-frontend:1.0
    container_name: project-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

